### PR TITLE
fix cstyle issues in ./src/istgt_iscsi_param.h

### PR DESCRIPTION
**Pull request by danimart1991**
Fixes https://github.com/openebs/openebs/issues/2024

### CODE REVIEW

**Review by utkarshmani1997 — APPROVED** [review]
LGTM

**Review by vishnuitta — APPROVED** [review]
changes are good

**Review by vishnuitta — CHANGES_REQUESTED** [review]
cstyle check is still showing errors:
```
./cstyle.pl src/istgt_iscsi_param.h 
src/istgt_iscsi_param.h: 29: #define followed by space instead of tab
src/istgt_iscsi_param.h: 55: line > 80 characters
src/istgt_iscsi_param.h: 56: line > 80 characters
src/istgt_iscsi_param.h: 58: line > 80 characters
```
Request to fix these errors

**Review by vishnuitta — APPROVED** [review]
changes are fine. I hadn't took your file to verify during my previous comment. Sorry for the mistake.

**Pull request merged**
