### PR TITLE
[TA4891] Adding debug logs for replica thread to ease the debugging

### PR DESCRIPTION
**Pull request by mynktl**
Task:
- Adding debug messages in the data connection module of replication to ease the debugging.

Signed-off-by: mayank <mayank.patel@cloudbyte.com>

### CODE REVIEW

**Review by vishnuitta — COMMENTED** [review]
changes looks good..
few more places - inform_mgmt_conn and inform_data_conn

**Comment by vishnuitta** [comment]
please add log in the caller of 'inform_mgmt_conn'

**Comment by mynktl** [comment]
@vishnuitta  I have added logs regarding informing error to mgmt/data connection in the respective caller function. Let me know if I have missed anything.

**Review by vishnuitta — APPROVED** [review]
thanks @mynktl .. changes are good

**Comment by vishnuitta** [comment]
can you cherry-pick this and the zfs one to v0.8.x branches @mynktl ?

**Pull request merged**
