### PR TITLE
fixed cstyle error in src/replication_test.c

### PR DESCRIPTION
**Pull request by HemangiS**
This PR solves issue (https://github.com/openebs/openebs/issues/2003)

### CODE REVIEW

**Review by vishnuitta — APPROVED** [review]
changes are good

**Review by vishnuitta — CHANGES_REQUESTED** [review]
travis is failing. There are compilation errors.

**Comment by vishnuitta** [comment]
compilation errors:
```
replication_test.c: In function ‘init_mdlist’:
replication_test.c:86:5: error: missing terminating " character [-Werror]
     "Failed to create
     ^
replication_test.c:87:17: error: missing terminating " character [-Werror]
     %s err(%d)\n"
                 ^
In file included from replication.h:18:0
                 from replication_test.c:13:
replication_test.c:86:5: error: missing terminating " character
     "Failed to create
     ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:87:6: error: ‘s’ undeclared (first use in this function)
     %s err(%d)\n"
      ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:87:6: note: each undeclared identifier is reported only once for each function it appears in
     %s err(%d)\n"
      ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:87:8: error: expected ‘)’ before ‘err’
     %s err(%d)\n"
        ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:87:15: error: stray ‘\’ in program
     %s err(%d)\n"
               ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:87:17: error: missing terminating " character
     %s err(%d)\n"
                 ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:85:4: note: in expansion of macro ‘REPLICA_ERRLOG’
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c: In function ‘test_read_data’:
replication_test.c:221:6: error: missing terminating " character [-Werror]
      "received err(%d)
      ^
replication_test.c:222:17: error: missing terminating " character [-Werror]
      on fd(%d)\n"
                 ^
In file included from replication.h:18:0
                 from replication_test.c:13:
replication_test.c:221:6: error: missing terminating " character
      "received err(%d)
      ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_test.c:222:6: error: expected ‘)’ before ‘on’
      on fd(%d)\n"
      ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_test.c:222:15: error: stray ‘\’ in program
      on fd(%d)\n"
               ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_test.c:222:17: error: missing terminating " character
      on fd(%d)\n"
                 ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_log.h:54:26: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format=]
  repl_log(LOG_LEVEL_ERR, "%-18.18s:%4d: %-20.20s: " fmt,  \
                          ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_log.h:54:26: error: format ‘%d’ expects a matching ‘int’ argument [-Werror=format=]
  repl_log(LOG_LEVEL_ERR, "%-18.18s:%4d: %-20.20s: " fmt,  \
                          ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_log.h:54:26: error: format ‘%s’ expects a matching ‘char *’ argument [-Werror=format=]
  repl_log(LOG_LEVEL_ERR, "%-18.18s:%4d: %-20.20s: " fmt,  \
                          ^
replication_log.h:36:42: note: in definition of macro ‘repl_log’
  snprintf(_l + _off, sizeof (_l) - _off, fmt, ##__VA_ARGS__); \
                                          ^~~
replication_test.c:220:5: note: in expansion of macro ‘REPLICA_ERRLOG’
     REPLICA_ERRLOG(
     ^~~~~~~~~~~~~~
replication_test.c: In function ‘send_io_resp’:
replication_test.c:381:5: error: missing terminating " character [-Werror]
     "failed to write
     ^
replication_test.c:382:22: error: missing terminating " character [-Werror]
     on fd errno(%d)\n", errno);
                      ^
replication_test.c:521:18: error: missing terminating " character [-Werror]
   REPLICA_ERRLOG("Failed to initialize
                  ^
replication_test.c:522:28: error: missing terminating " character [-Werror]
    mdlist for replica(%d)\n", ctrl_port);
                            ^
replication_test.c:536:15: error: missing terminating " character [-Werror]
   REPLICA_LOG("conn_listen() failed
               ^
replication_test.c:537:22: error: missing terminating " character [-Werror]
    err:%d replica(%d)", errno, ctrl_port);
                      ^
replication_test.c:547:4: error: missing terminating " character [-Werror]
    "epoll_ctl() failed
    ^
replication_test.c:548:22: error: missing terminating " character [-Werror]
    err:%d replica(%d)"
                      ^
replication_test.c:576:4: error: missing terminating " character [-Werror]
    "epoll_ctl() failed
    ^
replication_test.c:577:22: error: missing terminating " character [-Werror]
    err:%d replica(%d)"
                      ^
replication_test.c:589:6: error: missing terminating " character [-Werror]
      "epoll error for
      ^
replication_test.c:590:19: error: missing terminating " character [-Werror]
      replica(%d)\n", ctrl_port);
                   ^
replication_test.c:600:8: error: missing terminating " character [-Werror]
        "Failed to read
        ^
replication_test.c:601:17: error: missing terminating " character [-Werror]
        from %d\n"
                 ^
replication_test.c:611:8: error: missing terminating " character [-Werror]
        "Failed to read
        ^
replication_test.c:612:17: error: missing terminating " character [-Werror]
        from %d\n"
                 ^
replication_test.c:630:7: error: missing terminating " character [-Werror]
       "Failed to read
       ^
replication_test.c:633:25: error: missing terminating " character [-Werror]
       bytes out of %lu\n"
                         ^
replication_test.c:653:8: error: missing terminating " character [-Werror]
        "failed to getch
        ^
replication_test.c:656:20: error: missing terminating " character [-Werror]
        out of %lu\n"
                    ^
replication_test.c:679:8: error: missing terminating " character [-Werror]
        "accept() failed
        ^
replication_test.c:680:26: error: missing terminating " character [-Werror]
        err:%d replica(%d)"
                          ^
replication_test.c:692:18: error: missing terminating " character [-Werror]
      REPLICA_LOG("Accepted connection
                  ^
replication_test.c:693:24: error: missing terminating " character [-Werror]
       on descriptor %d "
                        ^
replication_test.c:700:7: error: missing terminating " character [-Werror]
       "make_socket_non_blocking()
       ^
replication_test.c:701:23: error: missing terminating " character [-Werror]
       failed, errno:%d"
                       ^
replication_test.c:711:7: error: missing terminating " character [-Werror]
       "epoll_ctl() failed
       ^
replication_test.c:712:27: error: missing terminating " character [-Werror]
       errno:%d replica(%d)"
                           ^
replication_test.c:818:19: error: missing terminating " character [-Werror]
       REPLICA_LOG("Volume name:%s
                   ^
replication_test.c:821:21: error: missing terminating " character [-Werror]
        replica(%d)\n"
                     ^
replication_test.c:836:9: error: missing terminating " character [-Werror]
         "sleeping for 60
         ^
replication_test.c:838:22: error: missing terminating " character [-Werror]
         replica(%d)\n"
                      ^
replication_test.c:879:9: error: missing terminating " character [-Werror]
         "Failed to write
         ^
replication_test.c:881:22: error: missing terminating " character [-Werror]
         replica(%d)\n"
                      ^
replication_test.c:930:9: error: missing terminating " character [-Werror]
         "failed to
         ^
replication_test.c:933:20: error: missing terminating " character [-Werror]
         %s off:%lu "
                    ^
replication_test.c:934:12: error: missing terminating " character [-Werror]
            "req:%lu read:%lu
            ^
replication_test.c:935:25: error: missing terminating " character [-Werror]
            replica(%d)\n"
                         ^
replication_test.c:956:8: error: missing terminating " character [-Werror]
        "Failed to send
        ^
replication_test.c:957:30: error: missing terminating " character [-Werror]
        response replica(%d)\n"
                              ^
replication_test.c:979:0: error: unterminated argument list invoking macro "REPLICA_ERRLOG"
 }
 
replication_test.c:380:4: error: ‘REPLICA_ERRLOG’ undeclared (first use in this function)
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
replication_test.c:380:4: error: expected ‘;’ at end of input
replication_test.c:380:4: error: expected declaration or statement at end of input
replication_test.c:380:4: error: expected declaration or statement at end of input
replication_test.c:380:4: error: expected declaration or statement at end of input
replication_test.c:352:14: error: unused variable ‘i’ [-Werror=unused-variable]
  int iovcnt, i, nbytes = 0;
              ^
replication_test.c:380:4: error: control reaches end of non-void function [-Werror=return-type]
    REPLICA_ERRLOG(
    ^~~~~~~~~~~~~~
At top level:
replication_test.c:349:1: error: ‘send_io_resp’ defined but not used [-Werror=unused-function]
 send_io_resp(int fd, zvol_io_hdr_t *io_hdr, void *buf)
 ^~~~~~~~~~~~
replication_test.c:240:1: error: ‘send_mgmt_ack’ defined but not used [-Werror=unused-function]
 send_mgmt_ack(int fd, zvol_op_code_t opcode, void *buf, char *replica_ip
 ^~~~~~~~~~~~~
replication_test.c:208:1: error: ‘test_read_data’ defined but not used [-Werror=unused-function]
 test_read_data(int fd, uint8_t *data, uint64_t len)
 ^~~~~~~~~~~~~~
replication_test.c:192:1: error: ‘check_for_err’ defined but not used [-Werror=unused-function]
 check_for_err(zvol_io_hdr_t *io_hdr)
 ^~~~~~~~~~~~~
replication_test.c:127:1: error: ‘fetch_update_io_buf’ defined but not used [-Werror=unused-function]
 fetch_update_io_buf(zvol_io_hdr_t *io_hdr, uint8_t *user_data
 ^~~~~~~~~~~~~~~~~~~
replication_test.c:107:1: error: ‘write_metadata’ defined but not used [-Werror=unused-function]
 write_metadata(uint64_t offset, size_t len, uint64_t io_num)
 ^~~~~~~~~~~~~~
replication_test.c:100:1: error: ‘destroy_mdlist’ defined but not used [-Werror=unused-function]
 destroy_mdlist(void)
 ^~~~~~~~~~~~~~
replication_test.c:56:1: error: ‘init_mdlist’ defined but not used [-Werror=unused-function]
 init_mdlist(char *vol_name)
 ^~~~~~~~~~~
replication_test.c:50:1: error: ‘sig_handler’ defined but not used [-Werror=unused-function]
 sig_handler(int sig)
 ^~~~~~~~~~~
```

**Comment by mittachaitu** [comment]
Closing this PR as there were no updates on this PR from `4 Nov 2018`. We can re-open it at any time to incorporate the review comments.

**Pull request closed without merging**
