### PR TITLE
fmt(cstyle): cstyle fixes in ./src/istgt_lu_disk.c

### PR DESCRIPTION
**Pull request by ghost**
This commit fixes almost all errors reported by cstyle.
The errors not yet fixed are "line > 80 characters" and
preprocessor statement not in column 1.
The error that won't be fixed is improper boolean continuation
at line 9136.

### CODE REVIEW

**Comment by ghost** [comment]
@ashishranjan738 there are some errors that I haven't fixed. What do you think?

**Review by vishnuitta — CHANGES_REQUESTED** [review]
still, cstyle is failing.
You can check for any cstyle errors by doing './cstyle.pl src/istgt_lu_disk.c' from the istgt directory.

**Comment by ghost** [comment]
@vishnuitta Yes, I've done the cstyle error linter.

There are false positives for 'line > 80 characters'. For example, line 10902 and 10905 both have 74 characters, but the linter reports that the particular lines have > 80 characters.

**Comment by mittachaitu** [comment]
@edawine Can we rebase the PR with the latest changes?

**Comment by ghost** [comment]
@mittachaitu Hi, I've just rebased to the latest changes.

**Comment by mittachaitu** [comment]
> @mittachaitu Hi, I've just rebased to the latest changes.

Thanks for that @edawine we will continue reviews on it.

**Comment by mynktl** [comment]
Closing this PR due to inactivity. @edawine Feel free to reach out us.

**Pull request closed without merging**
